### ISSUE TITLE
Error: Could not connect to the database. Please try again later.

### ISSUE THREAD

**Issue by noaptus** [hjelmua/php-timeclock-with-bootsrap#1]
Can you please tell my why I have this error 

Error: Could not connect to the database. Please try again later.

All settings are as they should be in the config.inc.php

**Comment by hjelmua** [comment]
And you have created a database with the same username and password?

**Comment by noaptus** [comment]
Yes I have.
Kveðja
Bragi Austfjörð
Forstjóri Djáknans
Sími: 615-1978
bragi@djakninn.is
------------------
Best Regards
Bragi Austfjord
CEO Djakninn
Phone: +354-615-1978
bragi@djakninn.is
Ábyrgð varðandi móttöku á tölvupósti frá Djáknanum
Vinsamlegast athugið að innihalds tölvupósts og viðhengja kann að vera 
trúnaðarmál.  Hafir þú fyrir misgáning, mistök eða án sérstakrar 
heimildar tekið við tölvupósti og viðhengjum hans, er þess óskað að þér 
gætið fyllst trúnaðar, tilkynnið sendanda tafarlaust og eyðið 
tölvupóstinum.  Misbrestur getur varðað bótaábyrgð og refsingu.  
Samkvæmt fjárskiptalögum nr. 81/2003.
Confidentiality Note:
This message including attachment may contain information which is 
confidential. If you are not the intended recipient, please contact the 
sender and delete this message. If it has come to you in error or 
through mistake, you must take no action based on it, nor must you copy 
or show it to anyone. You are requested to treat in strict confidence 
and to notify us without delay and delete your copy.
Failure may entail civil and criminal liability. Based on act: 81/2003 
in Telecommunications
On 10 Nov 2016 14:37, hjelmua <notifications@github.com> wrote:And you have created a database with the same username and password?

**Comment by hjelmua** [comment]
The error message is there if either there is no connection to the database or that the username/password is incorrect. What server setup do you have? So I can test the same setup.

/J

**Comment by noaptus** [comment]
WHM 60.0 (build 17)

Mysql:

Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.6.34 - MySQL Community Server (GPL)
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)

cpsrvd 11.60.0.17
Database client version: libmysql - 5.1.73
PHP extension: mysqli


Apache Server Version: Apache/2.4.23 (Unix) OpenSSL/1.0.1e-fips 
mod_bwlimited/1.4


php version:


[root@hq ~]# php -v
PHP 5.6.27 (cli) (built: Nov 10 2016 21:20:13)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
     with the ionCube PHP Loader (enabled) + Intrusion Protection from 
ioncube24.com (unconfigured) v5.1.1, Copyright (c) 2002-2016, by ionCube 
Ltd.
     with Zend Guard Loader v3.3, Copyright (c) 1998-2014, by Zend 
Technologies
     with Suhosin v0.9.38, Copyright (c) 2007-2015, by SektionEins GmbH

**Comment by noaptus** [comment]
Did you get my last email?

**Comment by hjelmua** [comment]
Just testet in a similar setup. 

It is very important that these settings in config.inc.php are correct.
$db_hostname = "localhost";
$db_username = "timeclock"; //user you created for this database
$db_password = "passwordofyourchoise"; //passwordforuser
$db_name = "timeclock"; //name of database

If you can not get it right there are a few changes that you can try for debug purposes.
$db_hostname = "127.0.0.1"; //in case there is a error in the hosts file
$db_username = "root";
$db_password = "write roots password";

**Comment by noaptus** [comment]
the database configuration that I am using is databasename_db this is how cpanel creates my user and db name.

**Comment by hjelmua** [comment]
Well to my knowledge the database name on cpanel is 
"your-username"_databasename so you cold name it "your-username_phptimeclock
and the user with rights to the database could be your default user or a new user called phptimeclock.
so $db_username = "your-username_phptimeclock";

**Comment by noaptus** [comment]
what server did you use for this setup?

**Comment by IWireC** [comment]
I was having this same issue, with delete and edit time. I found the issue to be the include line for config.inc.php. I changed it from `include 'config.inc.php'; ` to `include '../config.inc.php';`

I am no expert with php or any computer programming, so I can't say if this is the correct fix, but it did correct my issue.
