### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by georgesouzafarias** [hjelmua/php-timeclock-with-bootsrap#10]
Hi,

I'm having problem with Administrator's login. 

I already have tried "admin" "admin" and I already have changed the admin's password in the DB, but I can't login.

Thanks

**Comment by kumaunix** [comment]
Do not change the password in the DB, it is encrypt and it cannot match. . .

**Comment by georgesouzafarias** [comment]
You're alright. 
Solved.
