### ISSUE TITLE
PHP Error - Create a New Officer.

### ISSUE THREAD

**Issue by georgesouzafarias** [hjelmua/php-timeclock-with-bootsrap#11]
Hello,

I'm trying to create a new officer and the follow error is shown.

PHP Fatal error:  Uncaught Error: Call to undefined function mysql_query() in /var/www/html/scripts/dropdown_get.php:40\nStack trace:\n#0 /var/www/html/admin/header_get.php(90): include()\n#1 /var/www/html/admin/usercreate.php(29): include('/var/www/html/a...')\n#2 {main}\n  thrown in /var/www/html/scripts/dropdown_get.php on line 40, referer: http://10.8.14.109/admin/index.php

Thank you.

**Comment by jrquint** [comment]
See issue #12
