### ISSUE TITLE
PHP 7 support is invalid due to use of mysql_* functions

### ISSUE THREAD

**Issue by jrquint** [hjelmua/php-timeclock-with-bootsrap#12]
Several scripts are still using the deprecated (as of PHP 5.5) mysql_* functions and need to be replaced with mysqli_* counterparts.  This would account for other issues regarding the admin and office pages listed previously

**Comment by jrquint** [comment]
Submitted a merge request from https://github.com/jrquint/php-timeclock-with-bootsrap that appears to fix these issues

**Comment by tbrats** [comment]
I am still getting blank pages?
