### ISSUE TITLE
PHP TimeClock reports pulling wrong date with datepicker

### ISSUE THREAD

**Issue by LukeARG** [hjelmua/php-timeclock-with-bootsrap#15]
Took me all day yesterday to figure this out. The time in reports was pulling in the wrong format, even after changing it in the settings under System Settings. Don't know much about codging but can navigate through it, after a bunch of digging found the settings to manually change the format in _"..\theme\templates"_ I found this code: 

`  $('#datepicker').datepicker({
      autoclose: true,
      format: 'd/m/yyyy',
 weekStart: 1,
	    todayHighlight: true
    });
    $('#datepicker1').datepicker({
      autoclose: true,
      format: 'd/m/yyyy',
       weekStart: 1,
	    todayHighlight: true
    });`

and changed the _format: d/m/yyyy_ to _format: _**m/d**_/yyyy_ 

Just posting it here so hopefully it can help someone else out. First time using github so not sure how to properly contribute.

Thanks for the program/script/free time clock!

**Comment by hjelmua** [comment]
I know this is a big issue in the code. There are two config files one in "root" and one in admin. If you want "US date". Change both config files.

**Comment by KungFuMonkie** [comment]
I've changed both config files for US dates, but on the reports, total_hours.php "Hours worked report" the calendar pop up still formats the dates as d/m/yyyy instead of the set m/d/yyyy. Can't seem to resolve this. Also, on adding time, the time drop down won't add the am/pm as set in configs either.

**Comment by hjelmua** [comment]
Unfortunately there are currently two sets of config.inc.php files (due to the date issue). One in / and one in /admin . You need to change both.

Best regards
J
