### ISSUE TITLE
Time edit issue

### ISSUE THREAD

**Issue by LukeARG** [hjelmua/php-timeclock-with-bootsrap#17]
Getting a bunch of error codes. Still dealing with other error first, so dealing with that for now..see below
![error](https://user-images.githubusercontent.com/37671655/38102190-8888f572-3350-11e8-9a98-03d13a8fa570.PNG)

**Comment by hjelmua** [comment]
I have not tested this on Windows and I am not sure about  your PHP version

**Comment by LukeARG** [comment]
Yeah I'm using Windows and PHP version: 7.0.28

Using this on a locally installed server bitnami

**Comment by LukeARG** [comment]
Found the error; the database name was wrong in the config file. Sorry, still new to this. Thank you.

![error](https://user-images.githubusercontent.com/37671655/38105514-40388c42-335a-11e8-9e10-a9c1e0f94417.PNG)
