### ISSUE TITLE
Problem creating users

### ISSUE THREAD

**Issue by alexchirinorojas** [hjelmua/php-timeclock-with-bootsrap#2]
Thank you very much for this excellent work
I have problem creating a user
Site www.kinesiologiaestetica.cl/time
user: admin
pass:admin
I have an office and a group, but when I try to create a new user, it does not show me the group or the office

please help

**Comment by alexchirinorojas** [comment]
![captura de pantalla 2017-01-24 a las 17 11 41](https://cloud.githubusercontent.com/assets/25329878/22264840/40fcbde6-e258-11e6-9c95-10e3c9956fb9.png)

**Comment by hjelmua** [comment]
Aah, there is a bit of really old code left without instructions. 
In the "create_tables.sql" there is a row that sets the password (encrypted)
INSERT INTO employees VALUES ('admin', NULL, 'xy.RY2HT1QTc2', 'administrator', '', '', '', 1, 1, 1, '');
The password is admin. Please log in and change that password ASAP.

**Comment by hjelmua** [comment]
sorry answered the wrong question. I will check it out ASAP

**Comment by hjelmua** [comment]
Can you check the following values in your database. 

In the table "groups" what are "groupname", groupid and officeid 
and
In the table Offices what are the values for officename and officeid

I made a test office on your site. I can see that I did not "bootstrap" some of the code on the "create office page". So my best guess is that the numbers in the database does not add upp until it is fixed. But I need to know that that's the problem.

**Comment by alexchirinorojas** [comment]
When I try to change the admin password I get this message
![captura de pantalla 2017-01-25 a las 10 47 09](https://cloud.githubusercontent.com/assets/25329878/22292789/b852094e-e2eb-11e6-8da1-970aaedb79d5.png)

**Comment by alexchirinorojas** [comment]
Site: www.kinesiologiaestetica.cl/time
user: admin
password:admin

**Comment by alexchirinorojas** [comment]
Please help me :)

**Comment by hjelmua** [comment]
To fix this issue I need to look at the database files. 

Can you check the following values in your database.

In the table "groups" what are "groupname", groupid and officeid
and
In the table Offices what are the values for officename and officeid

**Comment by alexchirinorojas** [comment]
![captura de pantalla 2017-01-30 a las 14 29 58](https://cloud.githubusercontent.com/assets/25329878/22433871/a81cbab8-e6f8-11e6-8617-b15807a56070.png)
![captura de pantalla 2017-01-30 a las 14 29 32](https://cloud.githubusercontent.com/assets/25329878/22433872/a81f837e-e6f8-11e6-845a-acbfa93edb5b.png)

**Comment by alexchirinorojas** [comment]
Please help me

**Comment by hjelmua** [comment]
I have found two issues. There is a problem with a new setup of the database, that I will look into. Also  are you using php 7 ? (I found that it does not work as expected on PHP 6)

**Comment by hjelmua** [comment]
There is a new tar file on https://pentarex.se/php-timeclock-with-bootsrap.tar it contains a new create_tables.sql and fixes for most issues. Later on the files on Github will be updated as well.

**Comment by alexchirinorojas** [comment]
Thank you very much, now it works fine, but I found another error .

When I want to modify or delete a user time, appears "Error: Could not connect to the database. Please try again later."

**Comment by alexchirinorojas** [comment]
![error](https://cloud.githubusercontent.com/assets/25329878/22484224/843f1038-e7e7-11e6-97cf-e944d940d9c5.JPG)

**Comment by alexchirinorojas** [comment]
Please help me, you are doing a great job and I want to congratulate you

**Comment by hjelmua** [comment]
I just tested to make a new user in the Office "Main Office" and group "Staff", then I deleted that user and it worked fine. You should change company name in time/admin/sysedit.php. I Suggest that you change the Admin password as well and that you also might want to change the URL for the app (Since it has been written here on Github).

**Comment by alexchirinorojas** [comment]
No, the error is in Miscellaneous / modify time..
When you click edit or delete, there is an error
![error111](https://cloud.githubusercontent.com/assets/25329878/22512439/c98d7b30-e877-11e6-8dc8-e3fe3ce7726d.jpg)

**Comment by alexchirinorojas** [comment]
Do not worry, I already solved it by modifying the configuration file that is in the admin folder

**Comment by alexchirinorojas** [comment]
Now everything works very well, I thank you and congratulations for this great work.

Just one last question:
How can I change, so that in the hour report, show the total as hours and not as a percentage?
in :: Reports/Hours worker report
![captura-de-pantalla-2017-02-02-a-las-17 05](https://cloud.githubusercontent.com/assets/25329878/22566421/8a83b5aa-e96a-11e6-8dd5-d902f5abc8f8.jpg)
![captura de pantalla 2017-02-02 a las 17 05 37](https://cloud.githubusercontent.com/assets/25329878/22566433/95f19c54-e96a-11e6-9d23-8d9bec38a3cd.png)

**Comment by hjelmua** [comment]
There is an error on your report with a empty "Salida". Maybe there is a calculation error that assumes there is  "Entrada"  first, I need to look into it again. Remove lonely "Salida" and have a look, it should then be "4 hours" total. Has the Admin report the same problem?

**Comment by groucha17** [comment]
Hello,

An up with an issue to the problem which is not one. It calculates from 00:00 till 17:51 automaticaly. This is why it is noticed 17.86 on your report.

Kind regards

Stéphane
