### ISSUE TITLE
Doubling timezone adjustment

### ISSUE THREAD

**Issue by IWireC** [hjelmua/php-timeclock-with-bootsrap#4]
I am trying this out on Ubuntu 16.10. When I transfer the database from an old version of timeclock current status report shows the correct time for old punches.  The settings are set to mirror original setup using timezone from server. 
 The issues I am having is the As of time, next to the Current Status Report title, is off by 4 hours. Also any new punches are also off by 4 hours. If I turn off use server time, the As of time corrects but then all the imported times ended up off by 4 hours.

Does anyone else have this issue and were you able to correct it?

**Comment by IWireC** [comment]
I switch back to mktime() in the leftmain.php and timeclock.php.

**Comment by hjelmua** [comment]
That is strange. I use a Ubuntu 16.10 on both devel and production servers. There is currently two included files and the error might be there. Also check that you don't use the legacy offset setting from the old version. I am swamped, but your fix is probably working as well.
