### ISSUE TITLE
Notes typed by the user are not recorded in the 'info' table.

### ISSUE THREAD

**Issue by deciorf** [hjelmua/php-timeclock-with-bootsrap#5]
Notes typed by the user are not recorded in the 'info' table.
The original program 'leftmain.php' used the function: '_**ereg_replace**_' which is deprecated. In this version was replaced by '_**preg_replace**_' but leaving the arguments intact does not work. I changed '_**[: alnum:]**_' to '_**A-Za-z0-9**_' and now it works.

//    $notes = ereg_replace("[^[:alnum:] \,\.\?-]","",strtolower($_POST['left_notes']));
//    $notes = preg_replace("[^[:alnum:] \,\.\?-]","",strtolower($_POST['left_notes']));
    $notes = preg_replace("([^A-Za-z0-9] \,\.\?-)", "", strtolower($_POST['left_notes']));

I'm not sure why does not work  '_**[: alnum:]**_'  in this case, and the impact of the change I made. Furthermore, I can see that '_**preg_replace("[^[:alnum:] \**_' is used in other three php programs: '**admin/timeedit.php**', '**admin/timedelete.php**' and '**admin/timedelete copy.php**'

Any suggestions or comments?

**Comment by hjelmua** [comment]
I uses old code to begin with. Someone needs to make fork and help out. Or a pull request.

**Comment by robao23** [comment]
> Las notas escritas por el usuario no se registran en la tabla 'información'. 
> El programa original 'leftmain.php' usó la función: ' _**ereg_replace**_ ' que está en desuso. En esta versión se reemplazó por ' _**preg_replace**_ ', pero dejar los argumentos intactos no funciona. Cambié ' _**[: alnum:]**_ ' a ' _**A-Za-z0-9**_ ' y ahora funciona.
> 
> // $ notes = ereg_replace ("[^ [: alnum:],.? -]", "", strtolower ($ _ POST ['left_notes'])); 
> // $ notes = preg_replace ("[^ [: alnum:],.? -]", ", strtolower ($ _ POST ['left_notes'])); 
> $ notes = preg_replace ("([^ A-Za-z0-9],.? -)", "", strtolower ($ _ POST ['left_notes']));
> 
> No estoy seguro de por qué no funciona ' _**[: alnum:]**_ ' en este caso, y el impacto del cambio que hice. Además, puedo ver que ' _** preg_replace ("[^ [: alnum:] **_ ' se usa en otros tres programas php: ' **admin / timeedit.php** ', ' **admin / timedelete.php** ' y ' **admin / timedelete copia.php** '
> 
> ¿Alguna sugerencia o comentario?

spaces removed to copy and paste

	$notes = preg_replace("([^ A-Za-z0-9],.? -)", "", strtolower($_POST ['left_notes']));
