### ISSUE TITLE
Bug with the Delete time option

### ISSUE THREAD

**Issue by groucha17** [hjelmua/php-timeclock-with-bootsrap#9]
Hello,
I have an error message when I would like to delete a previous registrated time. 

Warning: include(config.inc.php): failed to open stream: No such file or directory in /home/clients/ea27f7cbee09d7101a32496af37c62cf/web/pointeuse/admin/timedelete.php on line 29

Warning: include(config.inc.php): failed to open stream: No such file or directory in /home/clients/ea27f7cbee09d7101a32496af37c62cf/web/pointeuse/admin/timedelete.php on line 29

Warning: include(): Failed opening 'config.inc.php' for inclusion (include_path='.:/opt/php5.6/lib/php') in /home/clients/ea27f7cbee09d7101a32496af37c62cf/web/pointeuse/admin/timedelete.php on line 29
Error: Could not connect to the database. Please try again later.

What shall I do ?

Kind regards

Stéphane

**Comment by kumaunix** [comment]
Do you have the config.inc.php in the same folder? if Yes, check the configuration if correct....
